//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOTP_Entities : DbContext
    {
        public HOTP_Entities()
            : base("name=HOTP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblHOTP_Codes> tblHOTP_Codes { get; set; }
        public virtual DbSet<tblHOTP_Goals> tblHOTP_Goals { get; set; }
        public virtual DbSet<tblHOTP_Employees> tblHOTP_Employees { get; set; }
        public virtual DbSet<tblHOTP_ActionSteps> tblHOTP_ActionSteps { get; set; }
        public virtual DbSet<tblHOTP_EmployeeGoals> tblHOTP_EmployeeGoals { get; set; }
        public virtual DbSet<tblHOTP_Plan90> tblHOTP_Plan90 { get; set; }
    }
}
