//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHOTP_Goals
    {
        public tblHOTP_Goals()
        {
            this.tblHOTP_EmployeeGoals = new HashSet<tblHOTP_EmployeeGoals>();
        }
    
        public int GoalID { get; set; }
        public string GoalType { get; set; }
        public string YearEnding { get; set; }
        public string Pillar { get; set; }
        public string GoalName { get; set; }
        public string PillarGoalName { get; set; }
        public string Goal { get; set; }
        public string Status { get; set; }
        public string ResultsMeasured { get; set; }
        public string BestRating { get; set; }
        public Nullable<float> Rating1 { get; set; }
        public Nullable<float> Rating2 { get; set; }
        public Nullable<float> Rating3 { get; set; }
        public Nullable<float> Rating4 { get; set; }
        public Nullable<float> Rating5 { get; set; }
        public string Rating1Suffix { get; set; }
        public string Rating5Suffix { get; set; }
        public Nullable<float> Rating2End { get; set; }
        public Nullable<float> Rating3End { get; set; }
        public Nullable<float> Rating4End { get; set; }
        public string YearEndCalculation { get; set; }
        public string UnitsMeasuredIn { get; set; }
        public Nullable<int> NumDecimals { get; set; }
        public string ResultsEntered { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<bool> NonEditableByLeader { get; set; }
        public bool Jan { get; set; }
        public bool Feb { get; set; }
        public bool Mar { get; set; }
        public bool Apr { get; set; }
        public bool May { get; set; }
        public bool Jun { get; set; }
        public bool Jul { get; set; }
        public bool Aug { get; set; }
        public bool Sep { get; set; }
        public bool Oct { get; set; }
        public bool Nov { get; set; }
        public bool Dec { get; set; }
        public Nullable<float> JanScore { get; set; }
        public Nullable<float> FebScore { get; set; }
        public Nullable<float> MarScore { get; set; }
        public Nullable<float> AprScore { get; set; }
        public Nullable<float> MayScore { get; set; }
        public Nullable<float> JunScore { get; set; }
        public Nullable<float> JulScore { get; set; }
        public Nullable<float> AugScore { get; set; }
        public Nullable<float> SepScore { get; set; }
        public Nullable<float> OctScore { get; set; }
        public Nullable<float> NovScore { get; set; }
        public Nullable<float> DecScore { get; set; }
        public string OrgNotes { get; set; }
        public Nullable<float> Result { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ICollection<tblHOTP_EmployeeGoals> tblHOTP_EmployeeGoals { get; set; }
    }
}
