//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHOTP_Plan90
    {
        public tblHOTP_Plan90()
        {
            this.tblHOTP_ActionSteps = new HashSet<tblHOTP_ActionSteps>();
        }
    
        public int PlanID { get; set; }
        public int EmployeeGoalID { get; set; }
        public int Quarter { get; set; }
        public string Goal { get; set; }
    
        public virtual ICollection<tblHOTP_ActionSteps> tblHOTP_ActionSteps { get; set; }
        public virtual tblHOTP_EmployeeGoals tblHOTP_EmployeeGoals { get; set; }
    }
}
