//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHOTP_Employees
    {
        public tblHOTP_Employees()
        {
            this.tblHOTP_EmployeeGoals = new HashSet<tblHOTP_EmployeeGoals>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int SupervisorID { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string EmpStatus { get; set; }
        public string Email { get; set; }
        public bool Admin { get; set; }
        public bool Evaluations { get; set; }
    
        public virtual ICollection<tblHOTP_EmployeeGoals> tblHOTP_EmployeeGoals { get; set; }
    }
}
