//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHOTP_ActionSteps
    {
        public int ActionID { get; set; }
        public int PlanID { get; set; }
        public string ActionStep { get; set; }
        public string Result { get; set; }
        public string Status { get; set; }
    
        public virtual tblHOTP_Plan90 tblHOTP_Plan90 { get; set; }
    }
}
