//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHOTP_Codes
    {
        public int CodeId { get; set; }
        public string CodeKey { get; set; }
        public string Code { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
